# Generated by Django 5.0.6 on 2026-07-23 06:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_or_existing', models.CharField(choices=[('new', 'New'), ('existing', 'Existing')], max_length=10, verbose_name='New or Existing')),
                ('visit_date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('evc', models.CharField(help_text='Digits only, starting with 92', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter digits only, starting with 92 (12 digits total).', regex='^92\\d{10}$')], verbose_name='EVC')),
                ('visit_type', models.CharField(choices=[('retailer', 'Retailer'), ('dso', 'DSO'), ('stall', 'Stall'), ('wic', 'WIC')], max_length=20, verbose_name='Type')),
                ('bvs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='BVS')),
                ('bvs_imei', models.CharField(max_length=50, verbose_name='BVS IMEI')),
                ('rso_visit', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='RSO Visit')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('load_stock_range', models.CharField(choices=[('0-99', '0-99'), ('100-500', '100-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('above_5000', 'Above 5000')], max_length=15, verbose_name='Load Stock')),
                ('psim_stock', models.PositiveIntegerField(default=0, verbose_name='PSim Stock')),
                ('npsim_stock', models.PositiveIntegerField(default=0, verbose_name='NP Sim Stock')),
                ('mbb_stock', models.PositiveIntegerField(default=0, verbose_name='MBB Stock')),
                ('zong_avg_loading', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Zong - Average Loading')),
                ('zong_avg_sim_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Zong - Average Sim Sales')),
                ('jazz_avg_loading', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jazz - Average Loading')),
                ('jazz_avg_sim_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jazz - Average Sim Sales')),
                ('fascia_zong', models.BooleanField(default=False, verbose_name='Zong')),
                ('fascia_ufone', models.BooleanField(default=False, verbose_name='Ufone')),
                ('fascia_jazz', models.BooleanField(default=False, verbose_name='Jazz')),
                ('avh', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='AVH')),
                ('pos', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='POS')),
                ('promo_awareness', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='Promo Awareness')),
                ('bundle_awareness', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='Bundle Awareness')),
                ('fca_commitment', models.PositiveIntegerField(blank=True, null=True, verbose_name='FCA Commitment')),
                ('mnp_commitment', models.PositiveIntegerField(blank=True, null=True, verbose_name='MNP Commitment')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('management_comment', models.TextField(blank=True, verbose_name='Management Comment')),
                ('photo', models.ImageField(upload_to='visit_photos/', verbose_name='Photo 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='visit_photos/', verbose_name='Photo 2')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='hierarchy.franchiserecord', verbose_name='Franchise (FR ID)')),
                ('visited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]