# Generated by Django 6.0.3 on 2026-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketvisit',
            name='avh',
        ),
        migrations.RemoveField(
            model_name='marketvisit',
            name='pos',
        ),
        migrations.AddField(
            model_name='marketvisit',
            name='avh_jazz',
            field=models.BooleanField(default=False, verbose_name='Jazz'),
        ),
        migrations.AddField(
            model_name='marketvisit',
            name='avh_ufone',
            field=models.BooleanField(default=False, verbose_name='Ufone'),
        ),
        migrations.AddField(
            model_name='marketvisit',
            name='avh_zong',
            field=models.BooleanField(default=False, verbose_name='Zong'),
        ),
        migrations.AddField(
            model_name='marketvisit',
            name='pos_jazz',
            field=models.BooleanField(default=False, verbose_name='Jazz'),
        ),
        migrations.AddField(
            model_name='marketvisit',
            name='pos_ufone',
            field=models.BooleanField(default=False, verbose_name='Ufone'),
        ),
        migrations.AddField(
            model_name='marketvisit',
            name='pos_zong',
            field=models.BooleanField(default=False, verbose_name='Zong'),
        ),
    ]
