# Generated by Django 6.0.3 on 2026-07-23 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_marketvisit_avh_remove_marketvisit_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketvisit',
            name='visit_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
