# Generated by Django 5.0.6 on 2026-07-23 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_id', models.CharField(max_length=50, unique=True, verbose_name='FR ID')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bu', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='BU')),
                ('fr_status', models.CharField(blank=True, max_length=50, verbose_name='FR Status')),
                ('fr_city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='FR City')),
                ('fr_address', models.CharField(blank=True, max_length=255, verbose_name='FR Address')),
                ('arm_name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='ARM Name')),
                ('arm_emp_no', models.CharField(blank=True, max_length=50, verbose_name='ARM Emp #')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['region', 'fr_id'],
            },
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_password', models.CharField(max_length=128)),
                ('must_change_password', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
